// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MirWebAPI.Data;

namespace MirWebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180626220108_MonsterTable")]
    partial class MonsterTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rc1-32029")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MirWebAPI.Models.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alive");

                    b.Property<string>("Attack");

                    b.Property<string>("BC");

                    b.Property<string>("Cold");

                    b.Property<string>("Dark");

                    b.Property<string>("Defence");

                    b.Property<string>("Description");

                    b.Property<string>("Drop");

                    b.Property<string>("Experience");

                    b.Property<string>("Fire");

                    b.Property<string>("Holy");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Level");

                    b.Property<string>("Light");

                    b.Property<string>("Name");

                    b.Property<string>("NameKr");

                    b.Property<string>("Phantom");

                    b.Property<string>("Tame");

                    b.Property<string>("Wind");

                    b.HasKey("Id");

                    b.ToTable("Monsters");
                });

            modelBuilder.Entity("MirWebAPI.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
